import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import type { HandwritingMetrics } from './imageMetrics'
import type { TemplateSettings } from './templateCanvas'
import { canvasToBlob } from './templateCanvas'

const README_CONTENT = `# InkDNA 字迹工坊项目包

本项目用于手写字体采集与后续字体制作。

## 项目说明

当前阶段不声称自动生成商业可用字体。
请人工补写、审核字形后再进入字体编译流程。

## 文件说明

- \`glyph_manifest.csv\` - 字形清单，包含所有待采集字符
- \`collection_template.png\` - 采集模板，请打印后手写
- \`project.json\` - 项目元数据与笔迹分析指标

## 使用流程

1. 打印 \`collection_template.png\` 采集模板
2. 使用黑色中性笔在方格内手写对应字符
3. 拍照或扫描回传手写稿
4. 使用字形切分工具处理手写稿
5. 审核每个字形质量
6. 进入字体编译流程（如 FontForge、Glyphs 等）

## 注意事项

- 请保持书写风格一致
- 单字不要贴边
- 避免连笔过度影响识别
- 保留自然书写风格

---
Generated by InkDNA 字迹工坊
`

const PITCH_CONTENT = `# InkDNA 字迹工坊 - 演示讲稿

InkDNA 不是尝试一次性自动生成 7000 个完美汉字，而是把手写字体制作流程产品化。

## 核心价值

1. 上传一张手写参考图，提取笔迹密度、留白、粗细、倾斜等指标。
2. 输入目标文本，自动整理唯一字表和 glyph manifest。
3. 生成统一采集模板，让用户按规范补写缺字。
4. 导出项目包，进入人工审核和字体编译流程。

## 为什么这样做

直接用 AI 生成全量字体会遇到三个问题：字形容易写错、风格容易漂移、商业授权边界不清。
InkDNA 把 AI 放在辅助位，把最终字形交给人工采集与审核，从而保留真实个人笔迹。

## 后续路线

- 自动切分采集模板中的单字
- 相似度评分和异常字提醒
- 批量审核字形
- 连接 FontForge / fontTools 生成 TTF/OTF
- 桌面版批量处理扫描件
`

function buildAnalysisReport(metrics: HandwritingMetrics | null, uniqueChars: string[]): string {
  const metricLines = metrics
    ? [
        `- 墨迹密度：${(metrics.inkDensity * 100).toFixed(1)}%`,
        `- 留白比例：${(metrics.whitespace * 100).toFixed(1)}%`,
        `- 笔画粗细估算：${metrics.strokeWeight.toFixed(1)}px`,
        `- 整体倾斜角：${metrics.slant.toFixed(1)}°`,
        `- 清晰度：${(metrics.clarity * 100).toFixed(1)}%`,
        `- 二值化阈值：${metrics.threshold}`
      ].join('\n')
    : '- 尚未上传参考图，未生成笔迹指标。'

  return `# InkDNA 分析报告

## 字表

- 待采集唯一字符：${uniqueChars.length}
- 前 80 个字符：${uniqueChars.slice(0, 80).join(' ')}

## 笔迹指标

${metricLines}

## 采集建议

- 使用黑色中性笔或签字笔。
- 使用白纸，避免阴影、透视、反光。
- 每个字尽量在格内完整书写，不要贴边。
- 保留自然快写风格，不要刻意写成楷体。
- 扫描或正面拍摄后，再进行字形切分和人工审核。
`
}

export interface ExportProjectParams {
  targetText: string
  uniqueChars: string[]
  metrics: HandwritingMetrics | null
  templateSettings: TemplateSettings
  csvContent: string
  templateCanvas: HTMLCanvasElement | null
}

export async function exportProjectZip(params: ExportProjectParams): Promise<void> {
  const { targetText, uniqueChars, metrics, templateSettings, csvContent, templateCanvas } = params

  const zip = new JSZip()

  zip.file('README.md', README_CONTENT)
  zip.file('pitch.md', PITCH_CONTENT)
  zip.file('analysis_report.md', buildAnalysisReport(metrics, uniqueChars))
  zip.file('glyph_manifest.csv', '\uFEFF' + csvContent)

  const projectData = {
    createdAt: new Date().toISOString(),
    version: '0.1.0',
    targetText,
    uniqueChars,
    uniqueCharCount: uniqueChars.length,
    metrics: metrics ? {
      inkDensity: metrics.inkDensity,
      whitespace: metrics.whitespace,
      strokeWeight: metrics.strokeWeight,
      slant: metrics.slant,
      clarity: metrics.clarity,
      threshold: metrics.threshold,
      width: metrics.width,
      height: metrics.height
    } : null,
    templateSettings: {
      columns: templateSettings.columns,
      cellSize: templateSettings.cellSize,
      padding: templateSettings.padding,
      headerHeight: templateSettings.headerHeight,
      footerHeight: templateSettings.footerHeight
    }
  }
  zip.file('project.json', JSON.stringify(projectData, null, 2))

  if (templateCanvas) {
    const templateBlob = await canvasToBlob(templateCanvas, 'image/png')
    zip.file('collection_template.png', templateBlob)
  }

  const content = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  })

  const timestamp = new Date().toISOString().slice(0, 10).replace(/-/g, '')
  saveAs(content, `InkDNA_project_${timestamp}.zip`)
}

export function downloadTextFile(content: string, filename: string, addBom = true): void {
  const bom = addBom ? '\uFEFF' : ''
  const blob = new Blob([bom + content], { type: 'text/plain;charset=utf-8' })
  saveAs(blob, filename)
}

export async function downloadCanvasAsPng(canvas: HTMLCanvasElement, filename: string): Promise<void> {
  const blob = await canvasToBlob(canvas, 'image/png')
  saveAs(blob, filename)
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    const textarea = document.createElement('textarea')
    textarea.value = text
    textarea.style.position = 'fixed'
    textarea.style.left = '-9999px'
    document.body.appendChild(textarea)
    textarea.select()
    try {
      document.execCommand('copy')
      document.body.removeChild(textarea)
      return true
    } catch {
      document.body.removeChild(textarea)
      return false
    }
  }
}
